apiVersion: v1
data:
  ephemeral.properties: c2VjdXJlU3RvcmUudHlwZT1FcGhlbWVyYWwKdGVuYW50cz1tZWRhZAptZWRhZD1tZWRhZCxNZWRhZF9hZG1pbkAxMjM=
kind: Secret
metadata:
  annotations: {}
  name: edge-rtac
  namespace: folio
type: Opaque
