apiVersion: v1
data:
  DB_HOST: MTAuMC4xMC4xMjI=
  DB_NAME: bWV0YWRi
  DB_PORT: NTQzMg==
  DB_SSLMODE: cmVxdWlyZQ==
  DB_SUPERUSER: cG9zdGdyZXM=
  DB_SUPERUSER_PASSWORD: QWFzQDQ3NzA0Nzc=
  DB_SYSTEMUSER: bWV0YWRi
  DB_SYSTEMUSER_PASSWORD: QGFzMTIz
kind: Secret
metadata:
  annotations: {}
  name: metadb-db
  namespace: folio
type: Opaque
