apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-rtac
  namespace: folio
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-edge-rtac
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-edge-rtac
      name: edge-rtac
      namespace: folio
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -Dokapi_url=http://okapi -Dport=8080 -Dsecure_store_props=/etc/secure/ephemeral.properties
          envFrom:
            - secretRef:
                name: edge-rtac
                optional: false
          image: jed.ocir.io/axhxgarudf1b/edge-rtac:2.9.3-1.0.0
          imagePullPolicy: IfNotPresent
          name: edge-rtac
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/secure/ephemeral.properties
              name: edge-synq-secret
              subPath: ephemeral.properties
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: product
          operator: Equal
          value: ils
        - effect: NoExecute
          key: product
          operator: Equal
          value: ils
      volumes:
        - name: edge-synq-secret
          secret:
            defaultMode: 420
            secretName: edge-synq
