apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-oai-pmh
  namespace: folio
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-edge-oai-pmh
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-edge-oai-pmh
      namespace: folio
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: -Dokapi_url=http://okapi -Dport=8080 -Dsecure_store=Vault -Dsecure_store_props=/path/to/secure_store_props
          image: folioorg/edge-oai-pmh:2.9.1
          imagePullPolicy: IfNotPresent
          name: container-0
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: product
          operator: Equal
          value: ils
        - effect: NoExecute
          key: product
          operator: Equal
          value: ils
