apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: folio-metadb
  namespace: folio
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-folio-metadb
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-folio-metadb
      name: folio-metadb
      namespace: folio
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - ils
      containers:
        - env:
            - name: management.endpoints.web.base-path
              value: /admin
            - name: management.endpoints.web.exposure.include
              value: '*'
            - name: DB_NAME
              value: medad_metadb
          envFrom:
            - secretRef:
                name: metadb-db
                optional: false
          image: jed.ocir.io/axhxgarudf1b/folio-metadb:1.3.2.1.0.1
          imagePullPolicy: Always
          name: folio-metadb
          ports:
            - containerPort: 8081
              name: tcp
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 3000Mi
            requests:
              cpu: 50m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: product
          operator: Equal
          value: ils
        - effect: NoExecute
          key: product
          operator: Equal
          value: ils
