apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: mod-oa
  namespace: folio
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-oa
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        workload: folio_module
        workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-oa
      name: mod-oa
      namespace: folio
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - ils
      containers:
        - env:
            - name: GRAILS_SERVER_HOST
              value: mod-agreements
            - name: GRAILS_SERVER_PORT
              value: "8081"
            - name: server.port
              value: "8081"
            - name: OKAPI_SERVICE_PORT
              value: "9130"
            - name: OKAPI_SERVICE_HOST
              value: okapi
            - name: JAVA_OPTIONS
              value: -server -XX:+UseContainerSupport -XX:MaxRAMPercentage=55.0 -XX:+PrintFlagsFinal
            - name: EVENTS_PUBLISHER_BOOTSTRAP_SERVERS
              value: kafka2-headless.kafka-cluster.svc.cluster.local:9092
            - name: EVENTS_CONSUMER_BOOTSTRAP_SERVERS
              value: kafka2-headless.kafka-cluster.svc.cluster.local:9092
            - name: EVENTS_PUBLISHER_ZK_CONNECT
              value: kafka-zookeeper-headless:9092
            - name: EVENTS_CONSUMER_ZK_CONNECT
              value: kafka-zookeeper-headless:9092
          envFrom:
            - secretRef:
                name: db-connect
                optional: true
            - secretRef:
                name: oci-object-storage
                optional: false
            - secretRef:
                name: mod-agreements
                optional: false
          image: folioorg/mod-oa:2.0.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: mod-oa
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 6000Mi
            requests:
              cpu: 50m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            procMount: Default
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 900
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: product
          operator: Equal
          value: ils
        - effect: NoExecute
          key: product
          operator: Equal
          value: ils
