apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-serials-management
  namespace: folio
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-serials-management
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload: folio_module
        workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-serials-management
      name: mod-serials-management
      namespace: folio
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - ils
      containers:
        - envFrom:
            - secretRef:
                name: db-connect
                optional: true
          image: folioorg/mod-serials-management:2.0.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/health
              port: 8080
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: mod-serials-management
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /admin/health
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1500m
              memory: 6000Mi
            requests:
              cpu: 50m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            procMount: Default
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 90
            httpGet:
              path: /admin/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1200
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: product
          operator: Equal
          value: ils
        - effect: NoExecute
          key: product
          operator: Equal
          value: ils
