apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-login-medad-sso
  namespace: folio
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-login-medad-sso
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-login-medad-sso
      namespace: folio
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - ils
      containers:
        - envFrom:
            - secretRef:
                name: db-connect
                optional: false
            - configMapRef:
                name: mod-login-medad-sso
                optional: false
          image: jed.ocir.io/axhxgarudf1b/mod-login-medad-sso:1.4.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: mod-login-medad-sso
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 6000Mi
            requests:
              cpu: 50m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 600
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: product
          operator: Equal
          value: ils
        - effect: NoExecute
          key: product
          operator: Equal
          value: ils
