apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: mod-search
  namespace: folio
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-folio-mod-search
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-folio-mod-search
      namespace: folio
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - ils
      containers:
        - env:
            - name: INITIAL_LANGUAGES
              value: eng,ara,fre
            - name: INSTANCE_SUBJECTS_INDEXING_RETRY_ATTEMPTS
              value: "2"
            - name: KAFKA_EVENTS_CONCURRENCY
              value: "2"
            - name: KAFKA_AUTHORITIES_CONCURRENCY
              value: "2"
            - name: SPRING_KAFKA_CONSUMER_MAX-POLL-RECORDS
              value: "50"
            - name: OTEL_SERVICE_NAME
              value: mod-search
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:8081
            - name: OTEL_JAVAAGENT_ENABLED
              value: "true"
            - name: OKAPI_URL
              value: https://okapi.medadstg.com
          envFrom:
            - secretRef:
                name: db-connect
                optional: false
            - secretRef:
                name: mod-search
                optional: false
          image: jed.ocir.io/axhxgarudf1b/mod-search:5.0.5.1.0.7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: mod-search
          ports:
            - containerPort: 8081
              name: 8081tcp2
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 6000Mi
            requests:
              cpu: 50m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: product
          operator: Equal
          value: ils
        - effect: NoExecute
          key: product
          operator: Equal
          value: ils
