apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-reporting
  namespace: folio
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-reporting
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload: folio_module
        workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-reporting
      name: mod-reporting
      namespace: folio
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - ils
      containers:
        - image: jed.ocir.io/axhxgarudf1b/mod-reporting:1.3.1.1.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/health
              port: 12369
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: mod-reporting
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /admin/health
              port: 12369
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 6000Mi
            requests:
              cpu: 50m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            procMount: Default
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /admin/health
              port: 12369
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: product
          operator: Equal
          value: ils
        - effect: NoExecute
          key: product
          operator: Equal
          value: ils
