apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-worklists
  namespace: folio
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-worklists
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-worklists
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - ils
      containers:
        - env:
            - name: OTEL_SERVICE_NAME
              value: mod-worklists
            - name: OTEL_JAVAAGENT_ENABLED
              value: "true"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:8081
          envFrom:
            - secretRef:
                name: db-connect
            - secretRef:
                name: oci-object-storage
                optional: false
            - secretRef:
                name: mod-worklists
                optional: false
          image: jed.ocir.io/axhxgarudf1b/mod-worklists:3.8.8
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: mod-worklists
          ports:
            - containerPort: 8081
              name: 8081tcp02
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 10000Mi
            requests:
              cpu: 100m
              memory: 1000Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsUser: 0
          startupProbe:
            failureThreshold: 20
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: product
          operator: Equal
          value: ils
        - effect: NoExecute
          key: product
          operator: Equal
          value: ils
