apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-z3950-folio
  namespace: folio
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-net-z3950-folio
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-net-z3950-folio
      namespace: folio
    spec:
      containers:
        - env:
            - name: OKAPI_URL
              value: https://okapi.medadstg.com
            - name: OKAPI_TENANT
              value: medad
            - name: OKAPI_USER
              value: dev_admin
            - name: OKAPI_PASSWORD
              value: Medad_admin@123
          image: jed.ocir.io/axhxgarudf1b/net-z3950-folio:latest-74098
          imagePullPolicy: Always
          name: net-z3950-folio
          ports:
            - containerPort: 9997
              name: p9997
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerhub
        - name: oracle-reg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
