apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: folio
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-otel-collector
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-otel-collector
      namespace: folio
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: product
                    operator: In
                    values:
                      - ils
      containers:
        - env:
            - name: management.endpoints.web.base-path
              value: /admin
            - name: deleted
              value: eu01xx71936660c96e1a9cdd20b8a036FFFFNRAL
            - name: INSERT
              value: https://otlp.eu01.nr-data.net
            - name: NEW_RELIC_API_KEY
              value: 390f08845ecf437e0607fe80b0aeb24cFFFFNRAL
            - name: INSERT_NEW_RELIC_OTLP_ENDPOINT
              value: https://otlp.nr-data.net
          image: jed.ocir.io/axhxgarudf1b/otel-collector:1.0.2
          imagePullPolicy: Always
          name: otel-collector
          ports:
            - containerPort: 8081
              name: tcp
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 3000Mi
            requests:
              cpu: 50m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: product
          operator: Equal
          value: ils
        - effect: NoExecute
          key: product
          operator: Equal
          value: ils
