apiVersion: v1
kind: Service
metadata:
  name: app-ui
  namespace: folio
spec:
  ports:
    - name: 80tcp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-app-ui
  sessionAffinity: None
  type: ClusterIP
