apiVersion: v1
kind: Service
metadata:
  name: debezium
  namespace: folio
spec:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-debezium
  sessionAffinity: None
  type: ClusterIP
