apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: debezium-ui
  namespace: folio
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-debezium-ui
  sessionAffinity: None
  type: ClusterIP
