apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: edge-oai-pmh
  namespace: folio
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-edge-oai-pmh
  sessionAffinity: None
  type: ClusterIP
