apiVersion: v1
kind: Service
metadata:
  name: edge-rtac
  namespace: folio
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-edge-rtac
  sessionAffinity: None
  type: ClusterIP
