apiVersion: v1
kind: Service
metadata:
  name: ils-mcp-server
  namespace: folio
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-ils-mcp-server
  sessionAffinity: None
  type: ClusterIP
