apiVersion: v1
kind: Service
metadata:
  name: mod-reporting
  namespace: folio
spec:
  ports:
    - port: 12369
      protocol: TCP
      targetPort: 12369
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-reporting
  sessionAffinity: None
  type: ClusterIP
