apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: mod-erm-usage-harvester
  namespace: folio
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: http1
      port: 5701
      protocol: TCP
      targetPort: 5701
  selector:
    workload.user.cattle.io/workloadselector: deployment-folio-mod-erm-usage-harvester
  sessionAffinity: None
  type: ClusterIP
