apiVersion: v1
kind: Service
metadata:
  name: mod-linked-data
  namespace: folio
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    workload.user.cattle.io/workloadselector: deployment-folio-mod-linked-data
  sessionAffinity: None
  type: ClusterIP

