apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: mod-marc-migrations
  namespace: folio
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-marc-migrations
  sessionAffinity: None
  type: ClusterIP
