apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: folio
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 4318
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-otel-collector
  sessionAffinity: None
  type: ClusterIP
