apiVersion: v1
kind: Service
metadata:
  name: quality-stripes
  namespace: folio
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-quality-stripes
  sessionAffinity: None
  type: ClusterIP
