apiVersion: v1
kind: Service
metadata:
  name: synq-mock-service
  namespace: folio
spec:
  ports:
    - port: 7001
      protocol: TCP
      targetPort: 7001
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-synq-mock-service
  sessionAffinity: None
  type: ClusterIP
